# Generated by Django 4.2.16 on 2024-10-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='smaak',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
